<?php

namespace DesignPatterns\Decorator;
class QQDecorator extends BaseDecorator
{
    public function send()
    {
        parent::send(); // TODO: Change the autogenerated stub
        echo ' 发送QQ通知';
    }
}