<?php
namespace DesignPatterns\Decorator;
class WeChatDecorator extends BaseDecorator
{
    public function send()
    {
        parent::send(); // TODO: Change the autogenerated stub
        echo ' 发送微信通知';
    }
}
